\input texinfo @c -*- texinfo; coding:utf-8 -*-
@c %**start of header
@setfilename dir
@documentencoding utf-8
@settitle ITS Info directory
@c %**end of header
@copying
This file is released under the GNU Free Documentation License.
@end copying
@ifnottex
@node Top
@top ITS Info directory
These files document the Incompatible Time-sharing System.
@menu
* Introduction:(its-intro)Top. An initial primer to ITS.
* DDT Primer:(its-ddt-primer)Top. An introduction to DDT, the debugger and
and primary user shell for ITS.
* TTY:(its-tty)Top. ITS support for Teletypes and terminals.
@end menu
@end ifnottex
@bye
